# Generated by Django 5.1.1 on 2024-09-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='snippets',
        ),
    ]
